---
- name: "Check if variables are defined"
  ansible.builtin.include_tasks: check_variables.yml

- name: "Create LVs/FSes"
  ansible.builtin.include_tasks: lvm.yml
  when: sbf_dedicated_lv_opt or sbf_dedicated_lv_srv or sbf_dedicated_lv_log

- name: "Deploy SELinux policy"
  ansible.builtin.include_tasks: selinux.yml

- name: "Create user and group"
  ansible.builtin.include_tasks: usersgroups.yml

- name: "Prepare Springboot root structures"
  ansible.builtin.include_tasks: directories.yml

- name: "Install SystemD service template"
  ansible.builtin.include_tasks: service.yml
