---

- name: Ensure the springboot-selinux RPM is present
  ansible.builtin.package:
    name: springboot-selinux
    state: present
  become: "{{ sbf_become }}"

- name: Ensure the springboot-selinux-devel RPM is present
  ansible.builtin.package:
    name: springboot-selinux-devel
    state: present
  become: "{{ sbf_become }}"
