---
- name: "Ensure the springboot-systemd RPM is present"
  ansible.builtin.package:
    name: springboot-systemd
    state: present
  become: "{{ sbf_become }}"

- name: "Enable the systemd Springboot target unit"
  ansible.builtin.systemd:
    name: "springboot.target"
    enabled: "{{ sbf_systemd_target_enabled }}"
    daemon_reload: true
  become: "{{ sbf_become }}"
