---

- name: Ensure the springboot-systemd RPM is present
  package:
    name: springboot-systemd
    state: present
  become: "{{ sbf_become }}"

- name: Enable the Install systemd Springboot target unit
  systemd:
    name: "springboot.target"
    enabled: sbf_systemd_target_enabled
    daemon_reload: yes
  become: "{{ sbf_become }}"
