---

- name: "Check for mandatory variables"
  ansible.builtin.fail:
    msg: "{{ item }} was not defined. Please check the role documentation."
  when: vars[item] is not defined
  loop:
    - sbi_appname
    - sbi_app_version
    - sbi_appjarname
    - sbi_java_version
    - sbi_java_flavour

- name: "Check for reserved variables"
  ansible.builtin.fail:
    msg: "{{ item }} variable is reserved for the role ansible-role-springboot ! Shouldn't be set/initialized !"
  when: vars[item] is defined
  loop:
    - sbi_service_stat_result
    - sbi_systemd_result
    - sbi_instance_stat_result
    - sbi_proc_stat_result
    - sbi_wait_for_pid
    - sbi_pkill_output_cmd
    - sbi_find_conf_files

- name: "Check consistentcy for dynamic libraries enabling"
  ansible.builtin.fail:
    msg: "Variable sbi_dynlib_dir_property must be defined when sbi_enable_dynlibs is true !"
  when: sbi_enable_dynlibs and sbi_dynlib_dir_property is not defined

- name: "Check consistentcy for JVM memory options"
  ansible.builtin.fail:
    msg: "Variable sbi_memory_max_heapsize_mb must be greater than or equal to sbi_memory_min_heapsize_mb !"
  when: sbi_memory_max_heapsize_mb < sbi_memory_min_heapsize_mb
