- name: "Install java"
  package:
    name: java-{{ sbi_java_version }}-{{ sbi_java_flavour }}-headless.x86_64
    state: present
  become: "{{ sbi_become }}"
  when: sbi_java_flavour != "oracle" and sbi_java_version > 8

- name: "Create symlink to Java home"
  ansible.builtin.file:
    state: link
    dest: "{{ sbi_appbase }}/java_home"
    src: "/etc/alternatives/jre_{{ sbi_java_version }}_{{ sbi_java_flavour }}"
  become: "{{ sbi_become }}"
  when: sbi_java_flavour != "oracle" and sbi_java_version > 8

