---
# Remove Springboot service for RHEL 7/8
# - name: Stop service
#   ansible.builtin.service:
#     name: "{{ sbi_service_name }}"
#     state: stopped
#   become: "{{ sbi_become }}"    

- name: Disable spring boot service
  systemd:
    name: "{{ sbi_service_name }}"
    enabled: false
    daemon_reload: yes
  become: "{{ sbi_become }}"

- name: Remove service env file
  ansible.builtin.file:
    path: "{{ sbi_service_env_filename }}"
    state: absent
  become: "{{ sbi_become }}"

- name: Remove systemd directory
  ansible.builtin.file:
    path: "/etc/systemd/system/springboot@{{ sbi_appname }}.d"
    state: absent
  become: "{{ sbi_become }}"
