---
- name: "Start Springboot instance"
  ansible.builtin.service:
    name: "{{ sbi_service_name }}"
    state: started
  become: "{{ sbi_become }}"
  when: sbi_run_handlers and sbi_become

- name: "Restart Springboot instance"
  ansible.builtin.service:
    name: "{{ sbi_service_name }}"
    state: restarted
  become: "{{ sbi_become }}"
  when: sbi_become

- name: "Cleanup workdir"
  ansible.builtin.file:
    path: "{{ sbi_workdir }}/{{ sbi_appjarname
      if (sbi_cleanup_entire_workdir is not defined or not sbi_cleanup_entire_workdir)
      else '' }}"
    state: absent
  become: "{{ sbi_become }}"
  when: sbi_run_handlers
