name: "Validate Ansible code"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'

  pull_request:
    branches: ["main", "release/**"]

  workflow_dispatch:

jobs:
  changelog:
    uses: ansible/ansible-content-actions/.github/workflows/changelog.yaml@main
    if: github.event_name == 'pull_request'

  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main

  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@main

#  unit-galaxy:
#    uses: ansible/ansible-content-actions/.github/workflows/unit.yaml@main
#
#  integration:
#    uses: ansible/ansible-content-actions/.github/workflows/integration.yaml@main
#
  all_green:
    if: ${{ always() }}
    needs:
      - changelog
      - sanity
      - ansible-lint
#      - integration
#      - unit-galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Synthetize results
        run: >-
         python -c "assert 'failure' not in set([
          '${{ needs.changelog.result }}',
          '${{ needs.sanity.result }}',
          '${{ needs.ansible-lint.result }}' ])"
#          '${{ needs.integration.result }}',
#          '${{ needs.unit-galaxy.result }}',
